service: aws-training-product-service # NOTE: update this with your service name
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  httpApi:
    cors: true
    # payload: "2.0"
    # disableDefaultEndpoint: false
  environment:
    PRODUCT_TABLE_NAME: aws_training_products
    STOCK_TABLE_NAME: aws_training_stock
    CREATE_PRODUCT_TOPIC_ARN: "arn:aws:sns:us-east-1:396572677717:aws-training-product-service-dev-createProductTopic-EGHHZ9QYYPCo"
  
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: 
        - !GetAtt catalogItemsQueue.Arn 

    - Effect: Allow
      Action: 
        - sns:Publish
      Resource: 
        - "arn:aws:sns:us-east-1:396572677717:aws-training-product-service-dev-createProductTopic-EGHHZ9QYYPCo"

    - Effect: Allow
      Action: 
        - dynamoDb:Query
        - dynamoDb:Scan
        - dynamoDb:GetItem
        - dynamoDb:PutItem
        - dynamoDb:UpdateItem
        - dynamoDb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:TransactWriteItems
      Resource: 
        - "arn:aws:dynamodb:us-east-1:396572677717:table/aws_training_products"
        - "arn:aws:dynamodb:us-east-1:396572677717:table/aws_training_stock"

resources:
  Resources:
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: aws-training-catalog-items-queue
        MessageRetentionPeriod: 86400

    createProductTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: "Create Product Topic"

    productCreatedSubscription:
      Type: "AWS::SNS::Subscription"
      Properties:
        Protocol: email
        TopicArn:
          Ref: createProductTopic
        Endpoint: contact@fareez.info

functions:

  get_products:
    handler: handlers/product-list.handler
    events:
      - httpApi:
          method: GET
          path: /products
      
  get_product_detail:
    handler: handlers/product-detail.handler
    events:
      - httpApi:
          method: GET
          path: /products/{id}

  create_product:
    handler: handlers/create-product.handler
    events:
      - httpApi:
          method: POST
          path: /products

  catalogBatchProcess:
    handler: handlers/catalog-batch-process.handler
    events:
      - sqs: 
          arn: !GetAtt catalogItemsQueue.Arn
          batchSize: 5

  data_seeder:
    handler: handlers/data-seeder.handler

plugins:
  - serverless-esbuild
